name = "mcp_toolkit_gleam"
version = "1.0.0"

description = "Production-ready Model Context Protocol (MCP) Toolkit - comprehensive server implementation in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "mikkihugo", repo = "mcp_toolkit_gleam" }

# Core dependencies (required for all functionality)
[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
jsonrpc = ">= 1.0.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 1.0.0"

# HTTP/WebSocket dependencies for all transport functionality
# mist = ">= 1.0.0 and < 3.0.0"
# wisp = ">= 0.10.0 and < 1.0.0"

# Build targets
[[binaries]]
name = "mcpstdio"
path = "./src/mcpstdio.gleam"

[[binaries]]
name = "mcpserver"
path = "./src/mcpserver.gleam"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.1 and < 3.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
