name = "mcp_toolkit"
version = "0.2.0"

description = "Gleam library for building Model Context Protocol servers and transports"
licences = ["Apache-2.0"]
repository = { type = "github", user = "mikan-laboratory", repo = "mcp_toolkit" }

# Core dependencies (required for all functionality)
[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
jsonrpcx = ">= 1.0.0 and < 2.0.0"
justin = ">= 1.0.1 and < 2.0.0"
gleam_erlang = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"

# HTTP/WebSocket dependencies for optional transport functionality
mist = ">= 1.0.0 and < 6.0.0"
# wisp = ">= 0.10.0 and < 1.0.0"

# Build targets
[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
birdie = ">= 1.2.7 and < 2.0.0"
