# Continuous Integration
name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up BEAM Environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1"
          rebar3-version: "3"

      - name: Download Dependencies
        run: gleam deps download

      - name: Run Tests
        run: gleam test

      - name: Check Formatting
        run: gleam format --check
