# Continuous Integration Pipeline
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    name: Run CI Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up BEAM Environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.12.0"
          rebar3-version: "3"

      - name: Download Project Dependencies
        run: gleam deps download

      - name: Execute Test Suite
        run: gleam test

      - name: Verify Code Formatting Standards
        run: gleam format --check
