# Dependency Update Automation
# Automatically checks for and updates Gleam dependencies

name: Dependency Updates

# Manual trigger from GitHub Actions UI
on:
  workflow_dispatch:

jobs:
  update-gleam-dependencies:
    name: Update Gleam Dependencies
    runs-on: ubuntu-latest

    # Required permissions for creating pull requests
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up BEAM Environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.12.0"
          rebar3-version: "3"

      # This command attempts to resolve conflicts and find the latest
      # compatible versions for all dependencies.
      - name: Update Gleam dependencies
        run: gleam deps update

      # This action checks if the update command changed any files.
      # If so, it creates a new branch and a pull request with the changes.
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update gleam dependencies"
          title: "Update Gleam Dependencies"
          body: |
            Automated dependency update.
            This PR was created by the `update-deps` workflow.
          branch: "chore/update-gleam-deps"
          delete-branch: true
