# Package Release Pipeline
# Automated publishing to Hex.pm when releases are created

name: Package Release

on:
  release:
    types: [published]

jobs:
  publish-package:
    name: Publish Package to Hex.pm
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up BEAM Environment
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1.11.1"
          rebar3-version: "3"

      - name: Download dependencies
        run: gleam deps download

      - name: Run final tests
        run: gleam test

      # Requires a HEX_API_KEY secret to be set in repository settings.
      - name: Publish to Hex.pm
        run: gleam publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
