# .github/workflows/test.yml
# This workflow uses separate jobs for setting up the environment and running tests.

name: test

# Controls when the workflow will run
on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  # This job sets up the environment and caches dependencies
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up BEAM tools
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1"
          rebar3-version: "3"

      # Generate a key for the cache based on the lock file
      - name: Cache key
        id: cache-key
        run: echo "key=gleam-deps-${{ hashFiles('gleam.lock') }}" >> $GITHUB_OUTPUT

      # Cache the downloaded dependencies to speed up subsequent runs
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: build/packages
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            gleam-deps-

      - name: Download dependencies
        # Only run 'gleam deps download' if the cache was not restored
        if: steps.cache.outputs.cache-hit != 'true'
        run: gleam deps download

  # This job runs the tests and formatting checks
  test:
    # This job depends on the 'setup' job completing successfully
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up BEAM tools
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          gleam-version: "1"
          rebar3-version: "3"

      # Generate the same cache key to find the correct cache
      - name: Cache key
        id: cache-key
        run: echo "key=gleam-deps-${{ hashFiles('gleam.lock') }}" >> $GITHUB_OUTPUT

      # Restore the cached dependencies from the setup job
      - name: Restore cached dependencies
        uses: actions/cache@v4
        with:
          path: build/packages
          key: ${{ steps.cache-key.outputs.key }}
          restore-keys: |
            gleam-deps-

      - name: Run tests
        run: gleam test

      - name: Check formatting
        run: gleam format --check src test
